spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/conference_app
    username: postgres
    password: Welcome
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
server:
  port: 8080
app:
  version: 0.0.1
debug: true